### ISSUE TITLE
[DOCS] Migrate fossunited dashboard usage manual from wiki to docs

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#645] opened 2024-09-30 07:12 UTC
### Documentation request

The manual for dashboard pages in the platform is added on wiki - https://fossunited.org/manual/ - that's managed from within Frappe desk. 

Move it to https://docs.fossunited.org

**Comment by rahulporuri** [comment] 2024-11-04 08:57
closing as addressed and duplicate of #669

**Closed as completed by rahulporuri** 2024-11-04 08:57 UTC
